In [2]:
import numpy as np
# a = np.array([1,2,3,4])
# print(a)
# print(a[1:3])

In [6]:
# Negative Indexing
# print(a[::-1])

[4 3 2 1]


In [7]:
# Slicing 2-D Arrayst
# arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
# print(arr[1,1:4])     #here it will fetch the second array slicing

[7 8 9]


In [5]:
a = np.array([[1,2,3,4,5]])
print(a)
x = a.ravel()
print(x)
y = np.append(x,10)
print(y)

[[1 2 3 4 5]]
[1 2 3 4 5]
[ 1  2  3  4  5 10]


In [3]:
a = np.array([1,2,3,4,5])
print(a)


[1 2 3 4 5]
