In [3]:
import numpy as np


In [69]:
arr = np.zeros(100).reshape(10,10)
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [25]:
arr = np.array([2,3,0,1,0,9])
l = np.where(arr>0)
print(l)

(array([0, 1, 3, 5]),)


In [27]:
# Create a zero one D vector of size 10 but 5 th indexing value should be replaced by 9.
arr = np.zeros(10)
arr[5]=9
print(arr)

[0. 0. 0. 0. 0. 9. 0. 0. 0. 0.]


In [38]:
# Create a 3×3 NumPy array of all True.
a = np.zeros((3,3),dtype=bool)+True
print(a)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [32]:
# Create a 4×4 array and extract its first row and last column.
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(arr)
x = arr[0][0:]
y = arr[:,3:]
print(x)
print(y)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[1 2 3 4]
[[ 4]
 [ 8]
 [12]
 [16]]


In [58]:
# Sorting a Numpy array with descending order.
arr = np.array([1,3,24,1,2,4,1,8])
x = np.sort(arr)
y=x[::-1]
print(y)

[24  8  4  3  2  1  1  1]


In [75]:
# Replace all odd numbers in a NumPy array with -1.
a = np.array([10,20,3,5,54,23])
l = np.where(a%2==1,-1,0)   #it return all even numbers
print(l)

[ 0  0 -1 -1  0 -1]


In [36]:
# Create a 1D array of 10 evenly spaced values between 5 and 50
arr = np.array(range(5,50))
print(np.split(arr,5))

[array([ 5,  6,  7,  8,  9, 10, 11, 12, 13]), array([14, 15, 16, 17, 18, 19, 20, 21, 22]), array([23, 24, 25, 26, 27, 28, 29, 30, 31]), array([32, 33, 34, 35, 36, 37, 38, 39, 40]), array([41, 42, 43, 44, 45, 46, 47, 48, 49])]


In [53]:
A1=np.array([1,2,3,4,5])
A2=np.array([1,4,7,8,5])
x = np.where(A1==A2)
print(x)
        

(array([0, 4]),)


In [13]:
# Create a random 3×2 matrix and find its maximum and minimum values.
a = np.array([[1,2,0,8,7,6]]).reshape(3,2)
x = np.max(a)
y = np.min(a)
print(x,y)

8 0


In [19]:
# Delete second column from given array.
A1=np.array([[1,2,3,4,5],[0,8,7,9,6]])
print(A1)
x = np.delete(A1,2,axis=1)
print(x)

[[1 2 3 4 5]
 [0 8 7 9 6]]
[[1 2 4 5]
 [0 8 9 6]]


In [78]:
# 7. Sorting a NumPy array based on a specific column.
# Ex: Array = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]]
# Note:(Sort records of 2 nd column)
Array = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])
x = int(input("Enter a Column number :"))
print(np.sort(Array[x]))

Enter a Column number : 0


[34 43 73]


In [4]:
a = np.array(range(1,21))
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [11]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
x =arr[arr%2==1]
print(x)

[1 3 5 7 9]


In [12]:
import numpy as np
arr = np.array([10,55,23,78,90,45,60])
x = np.count_nonzero(arr<50)
print(x)

3


## arr = np.array([1,2,3,5,3,4,9,5])
x = arr[0]

for i in arr:
    if x<i:
        x=i
print(x)
        
    
    

In [46]:
# Replace all values greater than 50 with -1.
arr = np.array([20,60,30,80,40,90])
x = np.where(arr>50,-1,arr)
print(x)

[20 -1 30 -1 40 -1]


In [60]:
# Extract all odd-position elements.
arr = np.array([20,60,30,80,40,90])
x = np.where(arr%2==1)
print(x)

(array([], dtype=int64),)


In [72]:
arr = np.arange(1,51)
result = arr[(arr%2==0) & (arr%3==0)]
print(result)

[ 6 12 18 24 30 36 42 48]


In [74]:
# Create a 4×4 matrix filled with numbers from 1 to 16.
ar = np.array(range(1,17)).reshape(4,4)
print(ar)
    

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [83]:
# Flatten a 2D array into 1D.
a = np.array([[1,2,3],[4,34,2]])
print(a.flatten())

[ 1  2  3  4 34  2]


In [1]:
import numpy as np

In [7]:
arr = np.array([1,2,3,4,5,6,7,8,9])
x = arr[arr%2==1]
print(x)

[1 3 5 7 9]


In [9]:
arr = np.arange(1, 21)
print(arr[arr%2==1])

[ 1  3  5  7  9 11 13 15 17 19]


In [17]:
arr = np.array([10, 20, 60, 70, 40, 80, 90])
print(np.count_nonzero(arr>50))

4


In [27]:
arr = np.arange(1, 51) 
x =arr[(arr%2==0) & (arr%3==0)]
print(x)

[ 6 12 18 24 30 36 42 48]


In [29]:
arr = np.array([12, 45, 67, 23, 89, 34])
print(np.max(arr))

89


In [30]:
arr = np.array([12, 45, 67, 23, 89, 34])
print(np.min(arr))

12


In [33]:
arr = np.array([1, 2, 3, 4, 5])
print(np.sum(arr))

15


In [36]:
arr = np.array([1,2,3,4,5,6,7,8])
print(np.where(arr%2==0,0,arr))

[1 0 3 0 5 0 7 0]


In [52]:
arr = np.array([15, 40, 10, 90, 50])
x=np.argmax(arr)
print(x)



3


In [53]:
arr = np.array([1,2,3,4,5])
print(arr[::-1])

[5 4 3 2 1]


In [59]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(np.count_nonzero(arr[arr%2==0]))
print(np.count_nonzero(arr[arr%2==1]))

5
5


In [85]:
arr = np.array([10,20,30,40,50])
x = np.average(arr)
result = arr[arr>x]
print(result)

[40 50]


In [90]:
arr = np.array([12, 45, 67, 89, 23, 89])
x = np.unique(arr)

print(x[-2])

67


In [88]:
arr = np.array([1,2,2,3,4,4,5,5,6])
print(np.unique(arr))

[1 2 3 4 5 6]


In [91]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
print(np.intersect1d(a,b))  # it return the common values in both arrays

[4 5]


In [102]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
print(np.setdiff1d(a,b))


[1 2 3]


In [106]:
# [[ 1  2  3  4  5]
#  [ 6  7  8  9 10]
#  [11 12 13 14 15]
#  [16 17 18 19 20]
#  [21 22 23 24 25]]
a = np.arange(1,26).reshape(5,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [110]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
x = np.sum(arr,axis=1)
print(x)

[ 6 15 24]


In [111]:
import numpy as np

arr = np.arange(2, 101)

primes = []

for num in arr:
    is_prime = True

    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            is_prime = False
            break

    if is_prime:
        primes.append(num)

print(np.array(primes))

[ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89
 97]


In [113]:
arr = np.arange(1, 101)
print(arr[arr%5==0])

[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


In [123]:
arr = np.array([10, -5, 20, -8, 15, -2,-6])
print(np.sum(arr<0))


4


In [139]:
arr = np.array([10, -5, 20, -8, 15, -2])
x = np.where(arr<0,0,arr)
print(x)


[10  0 20  0 15  0]


In [146]:
arr = np.arange(1, 101)
result = arr[(arr>=20) & (arr<=50)]
print(result)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50]


In [147]:
a = np.array([1,2,3])
b = np.array([1,2,3])
print(a==b)

[ True  True  True]


In [165]:
# [[ 1  2  3 ... 10]
#  [ 2  4  6 ... 20]
#  [ 3  6  9 ... 30]
#  ...
# ]
arr = np.arange(1,11)
table = arr.reshape(10,1)*arr
print(table)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [164]:
import numpy as np

arr = np.arange(1, 11)

table = arr.reshape(10, 1) * arr

print(table)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]
