In [1]:
import numpy as np

In [5]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a,b)
c = np.concatenate((a,b))  # it comibine both arraysa a and b
print(c)

[1 2 3 4] [5 6 7 8]
[1 2 3 4 5 6 7 8]


In [22]:
# join two tables with 2-d arrays
a1 = np.array([[1,2,3,4],[7,8,9,10]])
a2 = np.array([[1,20,30,40],[50,60,70,80]])
print(a1)
print(a2)
arr = np.concatenate((a1,a2),axis=1)
print(arr,f"the size of array is :{arr.ndim}")

[[ 1  2  3  4]
 [ 7  8  9 10]]
[[ 1 20 30 40]
 [50 60 70 80]]
[[ 1  2  3  4  1 20 30 40]
 [ 7  8  9 10 50 60 70 80]] the size of array is :2


In [30]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.stack((arr1,arr2))
print(arr1,arr1.ndim)
print(arr2,arr2.ndim)
print(arr,arr.ndim)

[1 2 3] 1
[4 5 6] 1
[[1 2 3]
 [4 5 6]] 2


In [33]:
# NumPy provides a helper function: hstack() to stack along rows
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.hstack((arr1,arr2))
print(arr)


[1 2 3 4 5 6]


In [36]:
arr1 = np.array([[1,2,3]])
arr2 = np.array([[4,5,6]])
arr = np.hstack((arr1,arr2))
print(arr)


[[1 2 3 4 5 6]]


In [37]:
arr1 = np.array([[1,2,3]])
arr2 = np.array([[4,5,6]])
arr = np.vstack((arr1,arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [40]:
arr1 = np.array([[1,2,3]])
arr2 = np.array([[4,5,6]])
arr = np.dstack((arr1,arr2))
print(arr,arr.ndim)

[[[1 4]
  [2 5]
  [3 6]]] 3
