In [ ]:
# Numpy array Shape

In [4]:
import numpy as np
# arr = np.array([[1,2,3,4],[5,6,7,8]])
# print(arr.shape)    #it will return (2, 4)

(2, 4)


In [9]:
# NumPy Array Reshaping
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr.reshape(4,3))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [10]:
# Reshape From 1-D to 3-D
print(arr.reshape(6,2,1))

[[[ 1]
  [ 2]]

 [[ 3]
  [ 4]]

 [[ 5]
  [ 6]]

 [[ 7]
  [ 8]]

 [[ 9]
  [10]]

 [[11]
  [12]]]


In [11]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(4,-1)
# newarr = arr.reshape(4, 2)

print(newarr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [17]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)


[1 2 3 4 5 6]


In [27]:
p = np.array([1,2,3,4,5,6])
sum=0
for i in np.nditer(p):
    sum+=i
print("the total sum is",sum)

the total sum is 21


In [33]:
p = np.array([1,2,3,4,5,6])
for i in np.nditer(p):
    print("Hello " + str(i))

Hello 1
Hello 2
Hello 3
Hello 4
Hello 5
Hello 6
