In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7,8])
x = np.where(arr==4)  #Find the indexes where the value is 4:
print(x)

(array([3]),)


In [3]:
arr = np.array([10, 14, 93, 41, 8, 7])
x = np.where(arr%2==1)   #who reminder is 1 their indexing display
print(x)

(array([2, 3, 5]),)


In [4]:
arr = np.array([10, 14, 93, 41, 8, 7])
x = np.where(arr%2==0)   #who reminder is 0 their indexing display
print(x)

(array([0, 1, 4]),)


In [6]:
arr = np.array([3,4,6,7,8])
x = np.searchsorted(arr,7)
print(x)

3


In [11]:
arr = np.array([3,4,6,7,8])
x = np.searchsorted(arr,3,side='right')
print(x)

2
