In [9]:
import numpy as np

In [ ]:
Splitting NumPy Arrays
Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits

In [7]:
arr = np.array([1,2,34,64,34,98])
print(arr)
x = np.split(arr,3)
print(x)

[ 1  2 34 64 34 98]
[array([1, 2]), array([34, 64]), array([34, 98])]


In [10]:
arr = np.array([23,12,42,16,64,34,65])
a = np.split(arr,3.5)
print(a)

[array([23, 12, 42]), array([16, 64]), array([34, 65])]


In [17]:
# Split Into Arrays
# The return value of the array_split() method is a list containing each of the split as an array.
# If you split an array into 3 arrays, you can access them from the result just like any array element
arr = np.array([1,2,3,4,5,6,60])
x = np.split(arr,3.5)
print(x)
print(x[0])
print(x[1])
print(x[2])

[array([1, 2, 3]), array([4, 5]), array([ 6, 60])]
[1 2 3]
[4 5]
[ 6 60]


In [18]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [19]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [20]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [5]:
import numpy as np

In [9]:
k = np.array([[1,2,3],[3,4,5]])
print(np.transpose(k))

[[1 3]
 [2 4]
 [3 5]]


In [12]:
k = np.array([1,2,3,3,4,5])
print(np.transpose(k))

[1 2 3 3 4 5]


In [17]:
k = np.array([1,2,3,3,4,5])
for i,v in np.ndenumerate(k):
    print("index",i,v)

index (0,) 1
index (1,) 2
index (2,) 3
index (3,) 3
index (4,) 4
index (5,) 5


In [23]:
k = np.array([1,2,3,3,4,5])
print(np.split(k,3))

[array([1, 2]), array([3, 3]), array([4, 5])]


In [27]:
t1 = np.array([1,2,3,4,5])
t2 = np.array([6,7,8,9,10])
k = np.hstack((t1,t2))
print(k)
print(k.ndim)

[ 1  2  3  4  5  6  7  8  9 10]
1


In [28]:
t1 = np.array([1,2,3,4,5])
t2 = np.array([6,7,8,9,10])
k = np.vstack((t1,t2))
print(k)
print(k.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2


In [30]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
print(np.dot(a1,a2))  

32


In [33]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
print(np.cross(a1,a2))

[-3  6 -3]


In [48]:
# a1 = np.array([1,2,3,4,5])
# a2 = np.array([10,20,30,40,50])
# k= np.concatenate((a1,a2))
print("hello")
a1 = np.array([1,2,3,4,5])
a2 = np.array([10,20,30,40,50])
k= np.concatenate((a1,a2))
k

hello


array([ 1,  2,  3,  4,  5, 10, 20, 30, 40, 50])

In [53]:
a = np.array([[1,2,3],[5,4,3]])
x = a.flatten()
x[1]=20
print(x)
print(a)

[ 1 20  3  5  4  3]
[[1 2 3]
 [5 4 3]]


In [55]:
a = np.array([[1,2,3],[5,4,3]])
x = a.ravel()
x[1]=20
print(x)
print(a)

[ 1 20  3  5  4  3]
[[ 1 20  3]
 [ 5  4  3]]


In [56]:
a = np.array([[1,2,3],[5,4,3]])
x = a.copy()
x[1]=20
print(x)
print(a)

[[ 1  2  3]
 [20 20 20]]
[[1 2 3]
 [5 4 3]]


In [57]:
a = np.array([[1,2,3],[5,4,3]])
x = a.view()
x[1]=20
print(x)
print(a)

[[ 1  2  3]
 [20 20 20]]
[[ 1  2  3]
 [20 20 20]]


In [61]:
x1 = np.array([[1,2],[3,4]])
x2 = np.array([[1,2],[3,4]])
print(x1)
print(x2)
print(x1@x2)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[ 7 10]
 [15 22]]


In [65]:
x1 = np.array([1,2,3,4])
x2 = np.array([1,2,3,4])
print(x1@x2)

30


In [69]:
a = np.array([1,2,3,4,0,0,23,3,0])
x = np.where(a==0)
p = np.delete(a,x)
print(p)

[ 1  2  3  4 23  3]


In [72]:
arr = np.array([1,2,3,4,5,6,7,8,9,1,2,3])
x = np.unique(arr)
print(x[-1])
print(x[-3])


9
7
