In [1]:
import numpy as np

In [4]:
arr = np.ones((10,10))
arr[1:-1,1:-1]=0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [11]:
a = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])
n = int(input("Enter the Number :"))
x = np.sort(a[n])
print(x)


Enter the Number : 2


[53 66 94]


In [14]:
a = np.linspace(5,50,10)
print(a)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [20]:
# Check if an array contains any NaN values.
a = np.array([1,2,3,np.isnan])
print(np.isnan(a).any())

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [30]:
A1=np.array([[1,2,3,4,5],[0,8,7,9,6]])
print(np.delete(A1,2,axis=1))

[[1 2 4 5]
 [0 8 9 6]]


In [36]:
A1=np.array([1,2,3,4,5])
A2=np.array([1,4,7,8,5])
print(np.intersect1d(A1,A2))
print(np.union1d(A1,A2))
print(np.setxor1d(A1,A2))

[1 4 5]
[1 2 3 4 5 7 8]
[2 3 7 8]


In [44]:
import numpy as np
# Perform the following:

# Replace 30 with 99.
# Add 5 to every element.
# Find elements greater than 25.
# Compute the average of the array.
arr = np.array([10, 20, 30, 40, 50])
arr[2]=99
print(arr)
for i in range(len(arr)):
    arr[i]+=5
print(arr)
x = np.where(arr>25)
print(arr[x])
x = np.average(arr)
print(x)

[10 20 99 40 50]
[ 15  25 104  45  55]
[104  45  55]
48.8
