In [1]:
import numpy as np

In [3]:
# The copy SHOULD NOT be affected by the changes made to the original array.
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0]=34
print(arr)
print(x)

[34  2  3  4  5]
[1 2 3 4 5]


In [8]:
# The view SHOULD be affected by the changes made to the original array.arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0]=34
print(arr)
print(x)

[34  2  3  4  5]
[34  2  3  4  5]


In [9]:
arr = np.array([1,2,3,4,5])
x = arr.view()  
x[0]=34
print(arr)
print(x)

[34  2  3  4  5]
[34  2  3  4  5]


In [10]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)


None
[1 2 3 4 5]


In [20]:
n = int(input("Enter Your Number : "))
a = [1,2,3,4,5]
for i in a:
    # print(i)
    if i==n:
        x = a.index(n)
        print(x)
    else:
        print("not found")
        brea



Enter Your Number :  8


not found
not found
not found
not found
not found


In [3]:
a = [1,2,3,4]
print(a.index(4))


3


In [2]:
s = frozenset({'gate','fate'})
s.add('rate')
print(s)

AttributeError: 'frozenset' object has no attribute 'add'

In [6]:
lst = [10,20,30,40,50]
s = set(lst)
print(s)

{40, 10, 50, 20, 30}


In [9]:
s = {10,20,30,40,50}
print(len(s))
print(max(s))
print(min(s))
print(sorted(s))
print(sum(s))
print(any(s))
print(all(s))

5
40
-50
[-50, 10, 20, 30, 40]
50
True
True


In [17]:
s = {12,15,13,44,54,67}
t = {'A','B','C'}
u = set()
# s.add('Hello')
# s.update(t)
# u = s.copy()
# s.remove(12)

s

{13, 15, 44, 54, 67}

In [29]:
d = {}
type(d)
d1 = {'101':'Anmol','102':'Sumit'}
print(d1['102'])

Sumit


In [37]:
courses = {'DAA':'CS','AQA':'ME','SYY':'CE'}
for k,v in enumerate(courses.items()):
    print(k,v)

for k in courses.keys():
    print(k)

for v in courses.values():
    print(v)

0 ('DAA', 'CS')
1 ('AQA', 'ME')
2 ('SYY', 'CE')
DAA
AQA
SYY
CS
ME
CE


In [42]:
courses = {'DAA':'CS','AQA':'ME','SYY':'CE'}
courses['PAA'] = 'krish' #add new key-value pair
courses['DAA'] = 'OOPs using JAVA'   # it will modfiy the key value pair
del(courses['DAA'])    # it will delete the key - value pair
del(courses)           #delete dictionary objects
courses

NameError: name 'courses' is not defined

In [44]:
courses = {'DAA':'CS','AQA':'ME','SYY':'CE'}
reversed(courses)
for k,v in reversed(courses.items()):     # the reverse fucntionn can work like this
    print(k,v)

SYY CE
AQA ME
DAA CS


In [55]:
d1 = {101:101,106:534}
print(len(d1))
print(max(d1))
print(min(d1))
print(sorted(d1))
print(any(d1))
print(all(d1))
print(sum(d1))

2
106
101
[101, 106]
True
True
207


In [63]:
c = {'CS101':'CPP','CS102':'DS','CS201':'OOP'}
d = {101:'krish',102:'Princy'}
print(c.get('CS101')) # with the help of these we can find the Value
print(c.get('CS102'))
c.update(d)
c.clear()
c

CPP
DS


{}

In [64]:
animals = {'Tigers':141,'Lion':152,'Leopard':110}
birds = {'Eagle':38,'Crow':3,'Parrot':2}
combined = {**animals,**birds}
print(combined)

{'Tigers': 141, 'Lion': 152, 'Leopard': 110, 'Eagle': 38, 'Crow': 3, 'Parrot': 2}


In [65]:
lst = [12,13,14,15,16]
d = dict.fromkeys(lst,25)
d

{12: 25, 13: 25, 14: 25, 15: 25, 16: 25}

In [66]:
lst = ['sachin','rahul','pawan','sonu']
d = dict.fromkeys(lst,50)
d
       

{'sachin': 50, 'rahul': 50, 'pawan': 50, 'sonu': 50}

In [72]:
import operator
d1 = {'Oil':230,'Clip':546,'Stud':450,'Nut':34}
print(d1)
d3 = sorted(d1.items(),key=operator.itemgetter(1))
d3

{'Oil': 230, 'Clip': 546, 'Stud': 450, 'Nut': 34}


[('Nut', 34), ('Oil', 230), ('Stud', 450), ('Clip', 546)]